url: https://flexwarm.com

title: Flexwarm

keywords: Flexwarm

description: Flexwarm

address: No.7, Xiâ€™an Road, Shawan Town, Panyu District, Guangzhou, China, 510000

tel: +86-020-34833982

email: contact@flexwarm.com

facebook: https://www.facebook.com/flexwarm/

twitter: https://twitter.com/getflexwarm

linkedin: https://www.linkedin.com/company/flexwarm/

youtube: https://www.youtube.com/channel/UC0NXHUd6SszgwJ5isP_gJOQ/

exclude:
  - README.md
